services:
  - type: web
    plan: free
    name: dl-BOT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/KemoXtech/Dl-all-in-one.git
    branch: Master
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: AUTH_USERS 
        sync: false
    autoDeploy: false
